export const testDevices = [
  {
    id: 'laptop-001',
    brand: 'Dell',
    model: 'Latitude 5420',
    category: 'Laptop',
    totalCount: 10,
    availableCount: 7,
  },
  {
    id: 'laptop-002',
    brand: 'HP',
    model: 'EliteBook 840',
    category: 'Laptop',
    totalCount: 8,
    availableCount: 5,
  },
  {
    id: 'tablet-001',
    brand: 'Apple',
    model: 'iPad Air',
    category: 'Tablet',
    totalCount: 15,
    availableCount: 12,
  },
  {
    id: 'camera-001',
    brand: 'Canon',
    model: 'EOS 2000D',
    category: 'Camera',
    totalCount: 5,
    availableCount: 3,
  },
  {
    id: 'tablet-002',
    brand: 'Samsung',
    model: 'Galaxy Tab S9',
    category: 'Tablet',
    totalCount: 12,
    availableCount: 9,
  },
];
